class CountryDialCodes {
  List<Map<String, String>> countryDialCodes = [
    {'country': 'Afghanistan', 'dialCode': '93'},
    {'country': 'Åland', 'dialCode': '358 18'},
    {'country': 'Albania', 'dialCode': '355'},
    {'country': 'Algeria', 'dialCode': '213'},
    {'country': 'American Samoa', 'dialCode': '1 684'},
    {'country': 'Andorra', 'dialCode': '376'},
    {'country': 'Angola', 'dialCode': '244'},
    {'country': 'Anguilla', 'dialCode': '1 264'},
    {'country': 'Antigua and Barbuda', 'dialCode': '1 268'},
    {'country': 'Argentina', 'dialCode': '54'},
    {'country': 'Armenia', 'dialCode': '374'},
    {'country': 'Artsakh', 'dialCode': '"374 47, 374 97"'},
    {'country': 'Aruba', 'dialCode': '297'},
    {'country': 'Ascension', 'dialCode': '247'},
    {'country': 'Australia', 'dialCode': '61'},
    {'country': 'Australian Antarctic Territory', 'dialCode': '672 1'},
    {'country': 'Australian External Territories', 'dialCode': '672'},
    {'country': 'Austria', 'dialCode': '43'},
    {'country': 'Azerbaijan', 'dialCode': '994'},
    {'country': 'Bahamas', 'dialCode': '1 242'},
    {'country': 'Bahrain', 'dialCode': '973'},
    {'country': 'Bangladesh', 'dialCode': '880'},
    {'country': 'Barbados', 'dialCode': '1 246'},
    {'country': 'Barbuda', 'dialCode': '1 268'},
    {'country': 'Belarus', 'dialCode': '375'},
    {'country': 'Belgium', 'dialCode': '32'},
    {'country': 'Belize', 'dialCode': '501'},
    {'country': 'Benin', 'dialCode': '229'},
    {'country': 'Bermuda', 'dialCode': '1 441'},
    {'country': 'Bhutan', 'dialCode': '975'},
    {'country': 'Bolivia', 'dialCode': '591'},
    {'country': 'Bonaire', 'dialCode': '599 7'},
    {'country': 'Bosnia and Herzegovina', 'dialCode': '387'},
    {'country': 'Botswana', 'dialCode': '267'},
    {'country': 'Brazil', 'dialCode': '55'},
    {'country': 'British Indian Ocean Territory', 'dialCode': '246'},
    {'country': 'British Virgin Islands', 'dialCode': '1 284'},
    {'country': 'Brunei Darussalam', 'dialCode': '673'},
    {'country': 'Bulgaria', 'dialCode': '359'},
    {'country': 'Burkina Faso', 'dialCode': '226'},
    {'country': 'Burundi', 'dialCode': '257'},
    {'country': 'Cambodia', 'dialCode': '855'},
    {'country': 'Cameroon', 'dialCode': '237'},
    {'country': 'Canada', 'dialCode': '1'},
    {'country': 'Cape Verde', 'dialCode': '238'},
    {'country': 'Caribbean Netherlands', 'dialCode': '"599 3, 599 4, 599 7"'},
    {'country': 'Cayman Islands', 'dialCode': '1 345'},
    {'country': 'Central African Republic', 'dialCode': '236'},
    {'country': 'Chad', 'dialCode': '235'},
    {'country': 'Chatham Island, New Zealand', 'dialCode': '64'},
    {'country': 'Chile', 'dialCode': '56'},
    {'country': 'China', 'dialCode': '86'},
    {'country': 'Christmas Island', 'dialCode': '61 89164'},
    {'country': 'Cocos (Keeling) Islands', 'dialCode': '61 89162'},
    {'country': 'Colombia', 'dialCode': '57'},
    {'country': 'Comoros', 'dialCode': '269'},
    {'country': 'Congo', 'dialCode': '242'},
    {'country': 'Congo, Democratic Republic of the', 'dialCode': '243'},
    {'country': 'Cook Islands', 'dialCode': '682'},
    {'country': 'Costa Rica', 'dialCode': '506'},
    {'country': 'Croatia', 'dialCode': '385'},
    {'country': 'Cuba', 'dialCode': '53'},
    {'country': 'Curaçao', 'dialCode': '599 9'},
    {'country': 'Cyprus', 'dialCode': '357'},
    {'country': 'Czech Republic', 'dialCode': '420'},
    {'country': 'Denmark', 'dialCode': '45'},
    {'country': 'Diego Garcia', 'dialCode': '246'},
    {'country': 'Djibouti', 'dialCode': '253'},
    {'country': 'Dominica', 'dialCode': '1 767'},
    {'country': 'Dominican Republic', 'dialCode': '"1 809, 1 829,\n1 849"'},
    {'country': 'East Timor (Timor-Leste)', 'dialCode': '670'},
    {'country': 'Easter Island', 'dialCode': '56'},
    {'country': 'Ecuador', 'dialCode': '593'},
    {'country': 'Egypt', 'dialCode': '20'},
    {'country': 'El Salvador', 'dialCode': '503'},
    {
      'country': 'Ellipso (Mobile Satellite service)',
      'dialCode': '"881 2, 881 3"'
    },
    {'country': 'EMSAT (Mobile Satellite service)', 'dialCode': '882 13'},
    {'country': 'Equatorial Guinea', 'dialCode': '240'},
    {'country': 'Eritrea', 'dialCode': '291'},
    {'country': 'Estonia', 'dialCode': '372'},
    {'country': 'Eswatini', 'dialCode': '268'},
    {'country': 'Ethiopia', 'dialCode': '251'},
    {'country': 'Falkland Islands', 'dialCode': '500'},
    {'country': 'Faroe Islands', 'dialCode': '298'},
    {'country': 'Fiji', 'dialCode': '679'},
    {'country': 'Finland', 'dialCode': '358'},
    {'country': 'France', 'dialCode': '33'},
    {'country': 'French Antilles', 'dialCode': '596'},
    {'country': 'French Guiana', 'dialCode': '594'},
    {'country': 'French Polynesia', 'dialCode': '689'},
    {'country': 'Gabon', 'dialCode': '241'},
    {'country': 'Gambia', 'dialCode': '220'},
    {'country': 'Georgia', 'dialCode': '995'},
    {'country': 'Germany', 'dialCode': '49'},
    {'country': 'Ghana', 'dialCode': '233'},
    {'country': 'Gibraltar', 'dialCode': '350'},
    {'country': 'Global Mobile Satellite System (GMSS)', 'dialCode': '881'},
    {
      'country': 'Globalstar (Mobile Satellite Service)',
      'dialCode': '"881 8, 881 9"'
    },
    {'country': 'Greece', 'dialCode': '30'},
    {'country': 'Greenland', 'dialCode': '299'},
    {'country': 'Grenada', 'dialCode': '1473'},
    {'country': 'Guadeloupe', 'dialCode': '590'},
    {'country': 'Guam', 'dialCode': '1 671'},
    {'country': 'Guatemala', 'dialCode': '502'},
    {
      'country': 'Guernsey',
      'dialCode': '"44 1481, 44 7781,\n44 7839, 44 7911"'
    },
    {'country': 'Guinea', 'dialCode': '224'},
    {'country': 'Guinea-Bissau', 'dialCode': '245'},
    {'country': 'Guyana', 'dialCode': '592'},
    {'country': 'Haiti', 'dialCode': '509'},
    {'country': 'Honduras', 'dialCode': '504'},
    {'country': 'Hong Kong', 'dialCode': '852'},
    {'country': 'Hungary', 'dialCode': '36'},
    {'country': 'Iceland', 'dialCode': '354'},
    {
      'country': 'ICO Global (Mobile Satellite Service)',
      'dialCode': '"881 0, 881 1"'
    },
    {'country': 'India', 'dialCode': '91'},
    {'country': 'Indonesia', 'dialCode': '62'},
    {'country': 'Inmarsat SNAC', 'dialCode': '870'},
    {'country': 'International Freephone Service (UIFN)', 'dialCode': '800'},
    {'country': 'International Networks', 'dialCode': '"882, 883"'},
    {'country': 'International Premium Rate Service', 'dialCode': '979'},
    {'country': 'International Shared Cost Service (ISCS)', 'dialCode': '808'},
    {'country': 'Iran', 'dialCode': '98'},
    {'country': 'Iraq', 'dialCode': '964'},
    {'country': 'Ireland', 'dialCode': '353'},
    {
      'country': 'Iridium (Mobile Satellite service)',
      'dialCode': '"881 6, 881 7"'
    },
    {
      'country': 'Isle of Man',
      'dialCode': '"44 1624, 44 7524,\n44 7624, 44 7924"'
    },
    {'country': 'Israel', 'dialCode': '972'},
    {'country': 'Italy', 'dialCode': '39'},
    {'country': 'Ivory Coast (Côte d\'Ivoire)', 'dialCode': '225'},
    {'country': 'Jamaica', 'dialCode': '"1 658, 1 876"'},
    {'country': 'Jan Mayen', 'dialCode': '47 79'},
    {'country': 'Japan', 'dialCode': '81'},
    {'country': 'Jersey', 'dialCode': '44 1534'},
    {'country': 'Jordan', 'dialCode': '962'},
    {'country': 'Kazakhstan', 'dialCode': '997 (also 7 until 2025)'},
    {'country': 'Kenya', 'dialCode': '254'},
    {'country': 'Kiribati', 'dialCode': '686'},
    {'country': 'Korea, North', 'dialCode': '850'},
    {'country': 'Korea, South', 'dialCode': '82'},
    {'country': 'Kosovo', 'dialCode': '383'},
    {'country': 'Kuwait', 'dialCode': '965'},
    {'country': 'Kyrgyzstan', 'dialCode': '996'},
    {'country': 'Laos', 'dialCode': '856'},
    {'country': 'Latvia', 'dialCode': '371'},
    {'country': 'Lebanon', 'dialCode': '961'},
    {'country': 'Lesotho', 'dialCode': '266'},
    {'country': 'Liberia', 'dialCode': '231'},
    {'country': 'Libya', 'dialCode': '218'},
    {'country': 'Liechtenstein', 'dialCode': '423'},
    {'country': 'Lithuania', 'dialCode': '370'},
    {'country': 'Luxembourg', 'dialCode': '352'},
    {'country': 'Macau', 'dialCode': '853'},
    {'country': 'Madagascar', 'dialCode': '261'},
    {'country': 'Malawi', 'dialCode': '265'},
    {'country': 'Malaysia', 'dialCode': '60'},
    {'country': 'Maldives', 'dialCode': '960'},
    {'country': 'Mali', 'dialCode': '223'},
    {'country': 'Malta', 'dialCode': '356'},
    {'country': 'Marshall Islands', 'dialCode': '692'},
    {'country': 'Martinique', 'dialCode': '596'},
    {'country': 'Mauritania', 'dialCode': '222'},
    {'country': 'Mauritius', 'dialCode': '230'},
    {'country': 'Mayotte', 'dialCode': '"262 269, 262 639"'},
    {'country': 'Mexico', 'dialCode': '52'},
    {'country': 'Micronesia, Federated States of', 'dialCode': '691'},
    {'country': 'Midway Island, USA', 'dialCode': '1 808'},
    {'country': 'Moldova', 'dialCode': '373'},
    {'country': 'Monaco', 'dialCode': '377'},
    {'country': 'Mongolia', 'dialCode': '976'},
    {'country': 'Montenegro', 'dialCode': '382'},
    {'country': 'Montserrat', 'dialCode': '1 664'},
    {'country': 'Morocco', 'dialCode': '212'},
    {'country': 'Mozambique', 'dialCode': '258'},
    {'country': 'Myanmar', 'dialCode': '95'},
    {'country': 'Namibia', 'dialCode': '264'},
    {'country': 'Nauru', 'dialCode': '674'},
    {'country': 'Nepal', 'dialCode': '977'},
    {'country': 'Netherlands', 'dialCode': '31'},
    {'country': 'Nevis', 'dialCode': '1 869'},
    {'country': 'New Caledonia', 'dialCode': '687'},
    {'country': 'New Zealand', 'dialCode': '64'},
    {'country': 'Nicaragua', 'dialCode': '505'},
    {'country': 'Niger', 'dialCode': '227'},
    {'country': 'Nigeria', 'dialCode': '234'},
    {'country': 'Niue', 'dialCode': '683'},
    {'country': 'Norfolk Island', 'dialCode': '672 3'},
    {'country': 'North Macedonia', 'dialCode': '389'},
    {'country': 'Northern Cyprus', 'dialCode': '90 392'},
    {'country': 'Northern Ireland', 'dialCode': '44 28'},
    {'country': 'Northern Mariana Islands', 'dialCode': '1 670'},
    {'country': 'Norway', 'dialCode': '47'},
    {'country': 'Oman', 'dialCode': '968'},
    {'country': 'Pakistan', 'dialCode': '92'},
    {'country': 'Palau', 'dialCode': '680'},
    {'country': 'Palestine, State of', 'dialCode': '970'},
    {'country': 'Panama', 'dialCode': '507'},
    {'country': 'Papua New Guinea', 'dialCode': '675'},
    {'country': 'Paraguay', 'dialCode': '595'},
    {'country': 'Peru', 'dialCode': '51'},
    {'country': 'Philippines', 'dialCode': '63'},
    {'country': 'Pitcairn Islands', 'dialCode': '64'},
    {'country': 'Poland', 'dialCode': '48'},
    {'country': 'Portugal', 'dialCode': '351'},
    {'country': 'Puerto Rico', 'dialCode': '"1 787, 1 939"'},
    {'country': 'Qatar', 'dialCode': '974'},
    {'country': 'Réunion', 'dialCode': '262'},
    {'country': 'Romania', 'dialCode': '40'},
    {'country': 'Russia', 'dialCode': '7'},
    {'country': 'Rwanda', 'dialCode': '250'},
    {'country': 'Saba', 'dialCode': '599 4'},
    {'country': 'Saint Barthélemy', 'dialCode': '590'},
    {'country': 'Saint Helena', 'dialCode': '290'},
    {'country': 'Saint Kitts and Nevis', 'dialCode': '1 869'},
    {'country': 'Saint Lucia', 'dialCode': '1 758'},
    {'country': 'Saint Martin (France)', 'dialCode': '590'},
    {'country': 'Saint Pierre and Miquelon', 'dialCode': '508'},
    {'country': 'Saint Vincent and the Grenadines', 'dialCode': '1 784'},
    {'country': 'Samoa', 'dialCode': '685'},
    {'country': 'San Marino', 'dialCode': '378'},
    {'country': 'São Tomé and Príncipe', 'dialCode': '239'},
    {'country': 'Saudi Arabia', 'dialCode': '966'},
    {'country': 'Senegal', 'dialCode': '221'},
    {'country': 'Serbia', 'dialCode': '381'},
    {'country': 'Seychelles', 'dialCode': '248'},
    {'country': 'Sierra Leone', 'dialCode': '232'},
    {'country': 'Singapore', 'dialCode': '65'},
    {'country': 'Sint Eustatius', 'dialCode': '599 3'},
    {'country': 'Sint Maarten (Netherlands)', 'dialCode': '1 721'},
    {'country': 'Slovakia', 'dialCode': '421'},
    {'country': 'Slovenia', 'dialCode': '386'},
    {'country': 'Solomon Islands', 'dialCode': '677'},
    {'country': 'Somalia', 'dialCode': '252'},
    {'country': 'South Africa', 'dialCode': '27'},
    {
      'country': 'South Georgia and the South Sandwich Islands',
      'dialCode': '500'
    },
    {'country': 'South Ossetia', 'dialCode': '995 34'},
    {'country': 'South Sudan', 'dialCode': '211'},
    {'country': 'Spain', 'dialCode': '34'},
    {'country': 'Sri Lanka', 'dialCode': '94'},
    {'country': 'Sudan', 'dialCode': '249'},
    {'country': 'Suriname', 'dialCode': '597'},
    {'country': 'Svalbard', 'dialCode': '47 79'},
    {'country': 'Sweden', 'dialCode': '46'},
    {'country': 'Switzerland', 'dialCode': '41'},
    {'country': 'Syria', 'dialCode': '963'},
    {'country': 'Taiwan', 'dialCode': '886'},
    {'country': 'Tajikistan', 'dialCode': '992'},
    {'country': 'Tanzania', 'dialCode': '255'},
    {
      'country': 'Telecommunications for Disaster Relief by OCHA',
      'dialCode': 'was 888'
    },
    {'country': 'Thailand', 'dialCode': '66'},
    {'country': 'Thuraya (Mobile Satellite service)', 'dialCode': '882 16'},
    {'country': 'Togo', 'dialCode': '228'},
    {'country': 'Tokelau', 'dialCode': '690'},
    {'country': 'Tonga', 'dialCode': '676'},
    {'country': 'Transnistria', 'dialCode': '"373 2, 373 5"'},
    {'country': 'Trinidad and Tobago', 'dialCode': '1 868'},
    {'country': 'Tristan da Cunha', 'dialCode': '290 8'},
    {'country': 'Tunisia', 'dialCode': '216'},
    {'country': 'Turkey', 'dialCode': '90'},
    {'country': 'Turkmenistan', 'dialCode': '993'},
    {'country': 'Turks and Caicos Islands', 'dialCode': '1 649'},
    {'country': 'Tuvalu', 'dialCode': '688'},
    {'country': 'Uganda', 'dialCode': '256'},
    {'country': 'Ukraine', 'dialCode': '380'},
    {'country': 'United Arab Emirates', 'dialCode': '971'},
    {'country': 'United Kingdom', 'dialCode': '44'},
    {'country': 'United States', 'dialCode': '1'},
    {
      'country': 'Universal Personal Telecommunications (UPT)',
      'dialCode': '878'
    },
    {'country': 'Uruguay', 'dialCode': '598'},
    {'country': 'US Virgin Islands', 'dialCode': '1 340'},
    {'country': 'Uzbekistan', 'dialCode': '998'},
    {'country': 'Vanuatu', 'dialCode': '678'},
    {
      'country': 'Vatican City State (Holy See)',
      'dialCode': '"39 06 698,\nassigned 379"'
    },
    {'country': 'Venezuela', 'dialCode': '58'},
    {'country': 'Vietnam', 'dialCode': '84'},
    {'country': 'Wake Island, USA', 'dialCode': '1 808'},
    {'country': 'Wallis and Futuna', 'dialCode': '681'},
    {'country': 'Yemen', 'dialCode': '967'},
    {'country': 'Zambia', 'dialCode': '260'},
    {'country': 'Zanzibar', 'dialCode': '255 24'},
    {'country': 'Zimbabwe', 'dialCode': '263'},
  ];
}
